// Code generated by dagger-compiler.  Do not edit.
package com.ef.daggertestproject;


import dagger.internal.Binding;
import javax.inject.Provider;

/**
 * A {@code Binder<CoolModule>} implementation which satisfies
 * Dagger's infrastructure requirements including:
 *
 * Being a {@code Provider<CoolModule>} and handling creation and
 * preparation of object instances.
 */
public final class CoolModule$$InjectAdapter extends Binding<CoolModule>
    implements Provider<CoolModule> {

  public CoolModule$$InjectAdapter() {
    super("com.ef.daggertestproject.CoolModule", "members/com.ef.daggertestproject.CoolModule", NOT_SINGLETON, CoolModule.class);
  }

  /**
   * Returns the fully provisioned instance satisfying the contract for
   * {@code Provider<CoolModule>}.
   */
  @Override
  public CoolModule get() {
    CoolModule result = new CoolModule();
    return result;
  }
}
