// Code generated by dagger-compiler.  Do not edit.
package com.ef.daggertestproject;


import dagger.internal.ModuleAdapter;

/**
 * A manager of modules and provides adapters allowing for proper linking and
 * instance provision of types served by {@code @Provides} methods.
 */
public final class CoolModule$$ModuleAdapter extends ModuleAdapter<CoolModule> {
  private static final String[] INJECTS = { };
  private static final Class<?>[] STATIC_INJECTIONS = { };
  private static final Class<?>[] INCLUDES = { };

  public CoolModule$$ModuleAdapter() {
    super(INJECTS, STATIC_INJECTIONS, false /*overrides*/, INCLUDES, true /*complete*/, false /*library*/);
  }

  @Override
  public CoolModule newModule() {
    return new com.ef.daggertestproject.CoolModule();
  }
}
